version: 0.2

env:
  secrets-manager:
    SONAR_TOKEN: Codebuild-DSS:SONAR_TOKEN
    DSSS3URI: Codebuild-DSS:DSSS3URI
  variables:
    DSSGLOBLIST: "dss_client-*.tgz"

phases:
  build:
    commands:
      - |
        build-wrapper-linux-x86-64 --out-dir bw-output \
          ./dss_client/scripts/build.sh
      - |
        sonar-scanner \
          -Dsonar.organization=openmpdk \
          -Dsonar.projectKey=OpenMPDK_dss-ecosystem \
          -Dsonar.sources=. \
          -Dsonar.cfamily.build-wrapper-output=bw-output \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.pullrequest.github.summary_comment=true \
          -Dsonar.pullrequest.provider=GitHub \
          -Dsonar.pullrequest.key=$(echo $GITHUB_REF | grep -oP "^refs/pull/\K[^/]+") \
          -Dsonar.pullrequest.base=${GITHUB_BASE_REF} \
          -Dsonar.pullrequest.branch=${GITHUB_HEAD_REF} \
          -Dsonar.pullrequest.github.repository=${GITHUB_REPOSITORY}
      - /stagemergeartifacts.sh

artifacts:
  files:
    - dss_client/dss_client-*.tgz
  discard-paths: yes
  name: builds/OpenMPDK_dss-ecosystem/$CODEBUILD_BUILD_NUMBER
