version: 0.2

env:
  secrets-manager:
    SONAR_TOKEN: Codebuild-DSS:SONAR_TOKEN
    DSSS3URI: Codebuild-DSS:DSSS3URI
  variables:
    SONAR_HOST_URL: https://sonarcloud.io
    DSSGLOBLIST: "dss_client-*.tgz"

phases:
  pre_build:
    commands:
      - ./dss_client/scripts/getrdddeps.sh
  build:
    commands:
      - |
        build-wrapper-linux-x86-64 --out-dir bw-output \
          ./dss_client/scripts/build.sh
      - |
        sonar-scanner \
          -Dsonar.branch.name="$([[ "$GITHUB_REF_NAME" != *"/merge" ]] && echo "$GITHUB_REF_NAME")" \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.pullrequest.github.summary_comment=true \
          -Dsonar.pullrequest.github.repository=OpenMPDK/dss-ecosystem \
          -Dsonar.pullrequest.key=$(echo $GITHUB_REF | grep -oP "^refs/pull/\K[^/]+") \
          -Dsonar.pullrequest.base=$GITHUB_BASE_REF \
          -Dsonar.pullrequest.branch=$GITHUB_HEAD_REF
  post_build:
    commands:
      - /stagemergeartifacts.sh

artifacts:
  files:
    - dss_client/dss_client-*.tgz
  discard-paths: yes
  name: builds/dss-ecosystem/dss_client/$CODEBUILD_BUILD_NUMBER
