version: 0.2

env:
  secrets-manager:
    SONAR_TOKEN: Codebuild-DSS:SONAR_TOKEN
    DSSS3URI: Codebuild-DSS:DSSS3URI
  variables:
    DSSGLOBLIST: "dss_client-*.tgz"

phases:
  build:
    commands:
      - |
        build-wrapper-linux-x86-64 --out-dir bw-output \
          ./dss_client/scripts/build.sh
      - |
        sonar-scanner \
          -Dsonar.branch.name="$([[ "$GITHUB_REF_NAME" == *"/merge" ]] && echo "$GITHUB_HEAD_REF" || echo "$GITHUB_REF_NAME")" \
          "$([[ "$GITHUB_REF_NAME" != *"/merge" ]] && echo "-Dsonar.branch.target=$GITHUB_REF_NAME" || echo '')" \
          -Dsonar.pullrequest.key=$(echo $GITHUB_REF | grep -oP "^refs/pull/\K[^/]+") \
          -Dsonar.pullrequest.base=${GITHUB_BASE_REF} \
          -Dsonar.pullrequest.branch=${GITHUB_HEAD_REF}
      - /stagemergeartifacts.sh

artifacts:
  files:
    - dss_client/dss_client-*.tgz
  discard-paths: yes
  name: builds/dss-ecosystem/dss_client/$CODEBUILD_BUILD_NUMBER
