version: 0.2

env:
  secrets-manager:
    SONAR_TOKEN: Codebuild-DSS:SONAR_TOKEN
    DSSS3URI: Codebuild-DSS:DSSS3URI
  variables:
    SONAR_HOST_URL: https://sonarcloud.io
    DSSGLOBLIST: "dss_client-*.tgz"

phases:
  pre_build:
    commands:
      # Download and extract RDD libs from prior dss-sdk target artifact for this branch
      - ./dss_client/scripts/getrdddeps.sh
  build:
    commands:
      # Build dss-client with Sonar build-wrapper for C/C++ static analysis
      - build-wrapper-linux-x86-64 --out-dir bw-output ./dss_client/scripts/build.sh
  post_build:
    commands:
      # Copy artifacts to branch dir if this is a merge
      - /stagemergeartifacts.sh
      # Copy build-wrapper output and build dir for later sonar-scanner stage
      - aws s3 cp --recursive bw-output "$DSSS3URI/cache/dss-ecosystem/$GITHUB_RUN_NUMBER/sonar/bw-output"
      - aws s3 cp --recursive dss_client/build "$DSSS3URI/cache/dss-ecosystem/$GITHUB_RUN_NUMBER/dss_client/build"

artifacts:
  files:
    - dss_client/dss_client-*.tgz
  discard-paths: yes
  name: builds/dss-ecosystem/$GITHUB_RUN_NUMBER
