version: 0.2

batch:
  fast-fail: false
  build-list:
    - identifier: dss_ai_benchmark
      env:
        variables:
          PROJECT: dss_ai_benchmark
    - identifier: dss_client
      env:
        variables:
          PROJECT: dss_client
    - identifier: dss_datamover
      env:
        variables:
          PROJECT: dss_datamover

phases:
  build:
    commands:
      - pycodestyle $PROJECT --show-source --show-pep8
