version: 0.2

env:
  secrets-manager:
    SONAR_TOKEN: Codebuild-DSS:SONAR_TOKEN
    DSSS3URI: Codebuild-DSS:DSSS3URI

phases:
  build:
    commands:
      - git ls-files '*.sh' | xargs -n1 shellcheck
