name: Build dss-ecosystem
on:
  push:
    branches:
      - master
      - stable/*
  pull_request:
    branches:
      - master
      - stable/*
    types:
      - opened
      - reopened
      - synchronize

jobs:
  dss-ecosystem:
    strategy:
      matrix:
        component:
          - dss-client
          - datamover
          - pycodestyle
    uses: OpenMPDK/DSS/.github/workflows/build-aws.yml@fix_branchname_for_ecr_image_tag
    with:
      component: ${{ matrix.component }}
      project-name: OpenMPDK_dss-ecosystem
    secrets: inherit
