name: Build dss-ecosystem
on:
  push:
    branches:
      - master
      - stable/*
  pull_request:
    branches:
      - master
      - stable/*
    types:
      - opened
      - reopened
      - synchronize

jobs:
  dss-client:
    uses: OpenMPDK/DSS/.github/workflows/build-aws.yml@test-workflows
    with:
      component: dss-client
      #project-name: OpenMPDK_dss-ecosystem
    secrets: inherit

  datamover:
    uses: OpenMPDK/DSS/.github/workflows/build-aws.yml@test-workflows
    with:
      component: datamover
      #project-name: OpenMPDK_dss-ecosystem
    secrets: inherit

  pycodestyle:
    uses: OpenMPDK/DSS/.github/workflows/build-aws.yml@test-workflows
    with:
      component: pycodestyle
      image: pycodestyle
      #project-name: OpenMPDK_dss-ecosystem
    secrets: inherit
