name: Build dss-ecosystem
on:
  push:
    branches:
      - master
      - stable/*
  pull_request:
    branches:
      - master
      - stable/*
    types:
      - opened
      - reopened
      - synchronize

env:
  PROJECT_NAME: OpenMPDK_dss-ecosystem
  WORKFLOW: OpenMPDK/DSS/.github/workflows/build-aws.yml@master

jobs:
  unit:
    uses: ${{ env.WORKFLOW }}
    with:
      component: unit-test
      project-name: ${{ env.PROJECT_NAME }}
    secrets: inherit
  lint:
    uses: ${{ env.WORKFLOW }}
    with:
      component: pycodestyle
      project-name: ${{ env.PROJECT_NAME }}
    secrets: inherit
  build:
    strategy:
      matrix:
        component:
          - dss-client
          - datamover
    uses: ${{ env.WORKFLOW }}
    with:
      component: ${{ matrix.component }}
      project-name: ${{ env.PROJECT_NAME }}
    secrets: inherit
  scan:
    uses: ${{ env.WORKFLOW }}
    with:
      component: sonar-scanner
      project-name: ${{ env.PROJECT_NAME }}
    secrets: inherit
    needs: [unit, build]
