name: Build dss-ecosystem
on:
  push:
    branches:
      - master
      - stable/*
  pull_request:
    branches:
      - master
      - stable/*
    types:
      - opened
      - reopened
      - synchronize

jobs:
  unit:
    uses: OpenMPDK/DSS/.github/workflows/build-aws.yml@master
    with:
      component: pytest
      project-name: OpenMPDK_dss-ecosystem
    secrets: inherit
  lint:
    uses: OpenMPDK/DSS/.github/workflows/build-aws.yml@master
    with:
      component: pycodestyle
      project-name: OpenMPDK_dss-ecosystem
    secrets: inherit
  build:
    strategy:
      matrix:
        component:
          - dss-client
          - datamover
    uses: OpenMPDK/DSS/.github/workflows/build-aws.yml@master
    with:
      component: ${{ matrix.component }}
      project-name: OpenMPDK_dss-ecosystem
    secrets: inherit
  scan:
    uses: OpenMPDK/DSS/.github/workflows/build-aws.yml@velomatt-patch-1
    with:
      component: sonar-scanner
      project-name: OpenMPDK_dss-ecosystem
      ext_image: sonarsource/sonar-scanner-cli:latest
    secrets: inherit
    needs: [unit, build]
