name: Build dss-ecosystem
on:
  pull_request:
    branches:
      - master
      - stable/*
    types:
      - opened
      - reopened
      - synchronize
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Transform ECR Image name
        if: startsWith(github.base_ref, 'stable') || startsWith(github.base_ref, 'master')
        id: ecr_image_name
        run: |
          ECR_IMAGE_NAME=${{ github.base_ref }}
          ECR_IMAGE_NAME=$(echo $ECR_IMAGE_NAME | tr '/' '_')
          echo "ECR_IMAGE_NAME=$ECR_IMAGE_NAME" >> $GITHUB_OUTPUT
      - name: Build dss-ecosystem on CodeBuild
        if: startsWith(github.base_ref, 'stable') || startsWith(github.base_ref, 'master')
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: OpenMPDK_dss-ecosystem
          compute-type-override: BUILD_GENERAL1_SMALL
          buildspec-override: ./buildspec/buildspec.yml
          image-override: "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-west-1.amazonaws.com/${{ secrets.REPOSITORY_NAME }}:dss-build_${{ steps.ecr_image_name.outputs.ECR_IMAGE_NAME }}"
  pycodestyle:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Run pycodestyle on CodeBuild
        if: startsWith(github.base_ref, 'stable') || startsWith(github.base_ref, 'master')
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: OpenMPDK_dss-ecosystem
          compute-type-override: BUILD_GENERAL1_SMALL
          buildspec-override: ./buildspec/buildspec-pycodestyle.yml
          image-override: "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-west-1.amazonaws.com/${{ secrets.REPOSITORY_NAME }}:pycodestyle"