name: Build dss-ecosystem
on:
  push:
    branches:
      - master
      - stable/*
  pull_request:
    branches:
      - master
      - stable/*
    types:
      - opened
      - reopened
      - synchronize

jobs:
  dss-client:
    uses: ./.github/workflows/build-aws.yml
    with:
      component: dss-client
    secrets: inherit

  datamover:
    uses: ./.github/workflows/build-aws.yml
    with:
      component: datamover
    secrets: inherit

  pycodestyle:
    uses: ./.github/workflows/build-aws.yml
    with:
      component: pycodestyle
      image: pycodestyle
    secrets: inherit
